name: Planner
description: "Planner des modes de journ√©e et des phases horaires"
version: "1.0.0"
slug: planner
init: false
arch:
  - amd64
  - armv7
  - aarch64
  - i386
startup: services
boot: auto
url: "https://github.com/jesuisla91/ha-addons"

ingress: true
ingress_port: 8099
panel_admin: true

webui: "http://[HOST]:[PORT:8099]"
ports:
  8099/tcp: null
map:
  - config:rw
options: {}
schema: {}
